name: Releases

on:
  push:
    tags:
      - '*release*'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: echo "TTS_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - run: echo "TTS_NAME=${TTS_TAG/-release/}" >> $GITHUB_ENV
      - run: echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" >> $GITHUB_ENV
      - run: echo "export TTS_VERSION=$TTS_NAME" >> .env

      - run: npm ci
      - run: npm run build
      - run: cp dist/index.html ./tts-playground.html
      - run: npm run test

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "./tts-playground.html"
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          name: TTS Playground ${{ env.TTS_NAME }}
          body: >
            Deployed at: [https://blueldr.github.io/tts-playground](https://blueldr.github.io/tts-playground)

            Download and run locally: [tts-playground.html](https://github.com/${{ env.GITHUB_REPOSITORY }}/releases/download/${{ env.TTS_TAG }}/tts-playground.html)
